import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import { cookies } from "next/headers";
import { Suspense } from "react";
import Footer from "@/components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

type Theme = "light" | "dark";

export default function RootLayout({ children }: any) {
	const theme: Theme = (cookies().get("theme")?.value as any) || "light";
	return (
		<html lang="en" className={`${theme}`}>
			<body className={inter.className}>
				<Navbar theme={theme} />
				<main className="min-h-[calc(100svh-60px)]">
					<Suspense fallback="Loading...">{children}</Suspense>
				</main>
				<Footer theme={theme} />
			</body>
		</html>
	);
}
